name: release-please

on:
  push:
    branches: [ main ]

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    env:
      GEM_NAME: has_stimulus_attrs
    steps:
      - uses: GoogleCloudPlatform/release-please-action@v3
        with:
          release-type: ruby
          package-name: ${{ env.GEM_NAME }}
          version-file: "lib/${{ env.GEM_NAME }}/version.rb"
